package com.waste2reward.ai
import android.Manifest
import android.content.pm.PackageManager
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
private val Leaf=Color(0xFF238B45);private val Dark=Color(0xFF124B2A);private val Mint=Color(0xFFEAF7EE);private val Gold=Color(0xFFF4B942);private val Bg=Color(0xFFF7FBF8)
data class Surplus(val food:String,val qty:String,val status:String,val recipient:String,val points:Int)
data class Waste(val name:String,val kg:String,val route:String,val points:Int)
class MainActivity:ComponentActivity(){private val camera=registerForActivityResult(ActivityResultContracts.RequestPermission()){};override fun onCreate(b:Bundle?){super.onCreate(b);if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)camera.launch(Manifest.permission.CAMERA);setContent{GreenPlate()}}}
@Composable fun GreenPlate(){var tab by remember{mutableIntStateOf(0)};var points by remember{mutableIntStateOf(680)};var surplus by remember{mutableStateOf(listOf(Surplus("Cooked rice","8 kg","Ready to donate","Community Kitchen",80),Surplus("Vegetable curry","5 kg","Pickup scheduled","Hope Shelter",50)))};var waste by remember{mutableStateOf(listOf(Waste("Food scraps","12.4 kg","Biogas / anaerobic digestion",120),Waste("Expired food","3.1 kg","Biogas / controlled organic processing",30)))};MaterialTheme(colorScheme=lightColorScheme(primary=Leaf,secondary=Gold,background=Bg)){Scaffold(containerColor=Bg,bottomBar={NavigationBar(containerColor=Color.White){listOf("⌂" to "Home","＋" to "Add","♻" to "Rescue","★" to "Rewards","☰" to "More").forEachIndexed{i,x->NavigationBarItem(selected=tab==i,onClick={tab=i},icon={Text(x.first,fontSize=21.sp)},label={Text(x.second)})}}}){pad->when(tab){0->Dashboard(points,waste,{tab=1},{tab=2},Modifier.padding(pad));1->AddFood({item->{surplus=surplus+item;points+=item.points;tab=2}},Modifier.padding(pad));2->Rescue(surplus,{i->{val s=surplus.toMutableList();s[i]=s[i].copy(status="Pickup confirmed");surplus=s}},Modifier.padding(pad));3->Rewards(points,Modifier.padding(pad));else->More(Modifier.padding(pad))}}}}
@Composable fun Dashboard(points:Int,waste:List<Waste>,add:()->Unit,rescue:()->Unit,m:Modifier){LazyColumn(m.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Green Plate",fontSize=31.sp,fontWeight=FontWeight.Bold,color=Dark);Text("Every plate matters.",fontSize=16.sp,color=Leaf)};Box(Modifier.size(55.dp).background(Leaf,CircleShape),contentAlignment=Alignment.Center){Text("🌱",fontSize=27.sp)}}};item{Card(colors=CardDefaults.cardColors(containerColor=Dark),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(20.dp)){Text("Today's impact",color=Color.White);Text("28.6 kg",fontSize=36.sp,fontWeight=FontWeight.Bold,color=Color.White);Text("food saved from disposal",color=Color.White.copy(alpha=.85f));Spacer(Modifier.height(12.dp));Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){Metric("12.4","kg to biogas");Metric("16.2","kg rescued")}}}};item{Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Button(onClick=add,modifier=Modifier.weight(1f)){Text("＋ ADD SURPLUS")};OutlinedButton(onClick=rescue,modifier=Modifier.weight(1f)){Text("RESCUE FOOD")}}};item{SectionTitle("AI Waste Forecast")};item{Card{Column(Modifier.padding(17.dp)){Text("Tomorrow's predicted food waste",fontWeight=FontWeight.Bold,fontSize=18.sp);Text("≈ 21.8 kg",fontSize=30.sp,fontWeight=FontWeight.Bold,color=Leaf);Text("Suggested action: reduce rice production by 8% and prepare smaller late-service batches.",color=Color.Gray)}}};item{SectionTitle("Food rescue pipeline")};item{Pipeline("🍲","Surplus registered","13.0 kg")};item{Pipeline("🤝","Matched with recipients","9.5 kg")};item{Pipeline("🛵","Delivery partner","7.2 kg")};item{Pipeline("❤️","People served","38 meals")};item{SectionTitle("Organic waste → Biogas")};items(waste){w->WasteCard(w)};item{Text("Edible surplus is routed for safe redistribution; unsuitable organic food can be routed to an appropriate anaerobic-digestion facility.",color=Color.Gray,fontSize=12.sp)}}}
@Composable fun Metric(a:String,b:String){Column(Modifier.background(Color.White.copy(alpha=.12f),RoundedCornerShape(12.dp)).padding(12.dp)){Text(a,fontWeight=FontWeight.Bold,color=Color.White,fontSize=19.sp);Text(b,color=Color.White,fontSize=11.sp)}};@Composable fun SectionTitle(t:String){Text(t,fontSize=21.sp,fontWeight=FontWeight.Bold,color=Dark)};@Composable fun Pipeline(icon:String,title:String,value:String){Row(Modifier.fillMaxWidth().background(Color.White,RoundedCornerShape(15.dp)).padding(14.dp),verticalAlignment=Alignment.CenterVertically){Text(icon,fontSize=24.sp);Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.Bold);Text(value,color=Color.Gray)};Text("✓",color=Leaf,fontSize=22.sp,fontWeight=FontWeight.Bold)}};@Composable fun WasteCard(w:Waste){Card{Row(Modifier.fillMaxWidth().padding(16.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(w.name,fontWeight=FontWeight.Bold);Text(w.kg+" • "+w.route,color=Color.Gray)};Text("+"+w.points,color=Leaf,fontWeight=FontWeight.Bold)}}}
@Composable fun AddFood(done:(Surplus)->Unit,m:Modifier){var food by remember{mutableStateOf("")};var qty by remember{mutableStateOf("")};LazyColumn(m.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(15.dp)){item{Text("Add Surplus Food",fontSize=29.sp,fontWeight=FontWeight.Bold,color=Dark);Text("Register safe, edible food before it becomes waste.",color=Color.Gray)};item{Card(colors=CardDefaults.cardColors(containerColor=Mint)){Column(Modifier.padding(17.dp)){Text("Quick AI estimate",fontWeight=FontWeight.Bold);Text("Use production, attendance and menu history to forecast surplus.",color=Color.Gray)}}};item{OutlinedTextField(food,{food=it},Modifier.fillMaxWidth(),label={Text("Food name")},placeholder={Text("e.g. cooked rice, chapati, curry")})};item{OutlinedTextField(qty,{qty=it},Modifier.fillMaxWidth(),label={Text("Quantity (kg)")})};item{Text("Food safety checklist",fontWeight=FontWeight.Bold,fontSize=19.sp,color=Dark)};item{Check("Prepared today / within safe holding time")};item{Check("Covered and handled hygienically")};item{Check("Not previously served or contaminated")};item{Button(onClick={done(Surplus(if(food.isBlank())"Cooked meal" else food,if(qty.isBlank())"5 kg" else qty,"Ready to donate","Matching in progress",40))},Modifier.fillMaxWidth().height(54.dp)){Text("PUBLISH SURPLUS",fontWeight=FontWeight.Bold)}}}}
@Composable fun Check(t:String){Row(Modifier.fillMaxWidth().background(Color.White,RoundedCornerShape(12.dp)).padding(14.dp)){Text("✓",color=Leaf,fontWeight=FontWeight.Bold);Spacer(Modifier.width(10.dp));Text(t)}}
@Composable fun Rescue(data:List<Surplus>,confirm:(Int)->Unit,m:Modifier){LazyColumn(m.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(13.dp)){item{Text("Food Rescue",fontSize=29.sp,fontWeight=FontWeight.Bold,color=Dark);Text("Match edible surplus with recipient organizations and delivery partners.",color=Color.Gray)};item{Card(colors=CardDefaults.cardColors(containerColor=Mint)){Column(Modifier.padding(17.dp)){Text("Delivery partner payment",fontWeight=FontWeight.Bold);Text("Record a delivery fee so the delivery partner can be paid. Live payment processing can be connected later.",color=Color.Gray)}}};items(data.withIndex().toList()){pair->val i=pair.index;val s=pair.value;Card{Column(Modifier.padding(17.dp)){Row{Text(s.food,Modifier.weight(1f),fontSize=18.sp,fontWeight=FontWeight.Bold);Text(s.qty,color=Leaf,fontWeight=FontWeight.Bold)};Text(s.recipient,color=Color.Gray);Spacer(Modifier.height(8.dp));Text(s.status,color=if(s.status.contains("confirmed"))Leaf else Gold,fontWeight=FontWeight.Bold);Spacer(Modifier.height(9.dp));Button(onClick={confirm(i)},modifier=Modifier.fillMaxWidth()){Text(if(s.status.contains("confirmed"))"PICKUP CONFIRMED" else "ASSIGN DELIVERY PARTNER")}}}}}}
@Composable fun Rewards(points:Int,m:Modifier){val rewards=listOf("🌱 Sponsor a sapling" to 500,"🥤 Reusable bottle" to 800,"👜 Reusable food bag" to 1000,"🎟 Partner eco coupon" to 1500);LazyColumn(m.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(13.dp)){item{Text("Green Rewards",fontSize=30.sp,fontWeight=FontWeight.Bold,color=Dark);Text(points.toString()+" Green Points",fontSize=20.sp,color=Leaf)};item{Card(colors=CardDefaults.cardColors(containerColor=Dark)){Column(Modifier.padding(19.dp)){Text("Keep saving food",color=Color.White);Text("Earn points for verified surplus rescue, correct waste routing and measurable impact.",color=Color.White,fontSize=16.sp)}}};items(rewards){r->Card{Row(Modifier.fillMaxWidth().padding(16.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(r.first,fontWeight=FontWeight.Bold,fontSize=17.sp);Text(r.second.toString()+" points",color=Color.Gray)};Button(onClick={}){Text(if(points>=r.second)"REDEEM" else "LOCKED")}}}}}}
@Composable fun More(m:Modifier){LazyColumn(m.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Text("More",fontSize=30.sp,fontWeight=FontWeight.Bold,color=Dark)};item{Info("🏫","For canteens, restaurants & hostels","Track production, surplus, rescue and organic waste.")};item{Info("📊","Impact dashboard","Food saved, meals served, waste diverted and estimated biogas feedstock.")};item{Info("🤖","AI forecasting","Replace demo forecasts with a trained model using sales, attendance, menu and weather data.")};item{Info("🛵","Delivery network","Recipient matching and delivery-partner assignment are demonstrated; live maps/payments need production integrations.")};item{Info("♻","Biogas route","Inedible/unsafe organic food stays out of the donation stream and can go to an appropriate anaerobic-digestion facility.")};item{Text("Demo mode: numbers and matches are sample data for the hackathon.",color=Color.Gray,fontSize=12.sp)}}}
@Composable fun Info(i:String,t:String,b:String){Card{Column(Modifier.padding(17.dp)){Text(i,fontSize=25.sp);Text(t,fontSize=18.sp,fontWeight=FontWeight.Bold,color=Dark);Text(b,color=Color.Gray)}}}
